# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f892fbb4d826e09b80252ec44431a1487919385163bc689fdd516a0734ac2da5901b3298ce1ab119a49abeaa9daecaeb4b0e4b952d954f10a86d32e95a37b7bf

test:
  secret_key_base: 26cc4b5d7ef1e7bf647d58f3e28c03ca60fec1b2957b42412f69729601d222ba96e028d024e1c8a7e425f886534add87d0c7c4519231b06272ba8a118043da8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
